Update patch set 3
Patch Set 3: Code-Review-1

Docker build fails:

Step 1/6 : FROM python:3.6-alpine3.9
 ---> 148efb059c7f
Step 2/6 : RUN apk --no-cache add --update         gcc         git         docker-cli         libc6-compat         libc-dev         libffi         libffi-dev         make         openssl-dev
 ---> Running in 8224140b679c
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  docker-cli (missing):
    required by: world[docker-cli]
The command '/bin/sh -c apk --no-cache add --update         gcc         git         docker-cli         libc6-compat         libc-dev         libffi         libffi-dev         make         openssl-dev' returned a non-zero code: 1

Patch-set: 3
Label: Code-Review=-1