Update patch set 4
Patch Set 4:

> Patch Set 3: Code-Review-1
> 
> Docker build fails:
> 
> Step 1/6 : FROM python:3.6-alpine3.9
>  ---> 148efb059c7f
> Step 2/6 : RUN apk --no-cache add --update         gcc         git         docker-cli         libc6-compat         libc-dev         libffi         libffi-dev         make         openssl-dev
>  ---> Running in 8224140b679c
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
> ERROR: unsatisfiable constraints:
>   docker-cli (missing):
>     required by: world[docker-cli]
> The command '/bin/sh -c apk --no-cache add --update         gcc         git         docker-cli         libc6-compat         libc-dev         libffi         libffi-dev         make         openssl-dev' returned a non-zero code: 1

Bumped to python:3.6-alpine3.10 which provides docker-cli

Patch-set: 4
Reviewer: Gerrit User 251 <251@4cada01b-0314-4fe0-84a1-f9ddc89863f9>
Label: Verified=0